2018-08-21 13:05:56,002 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-21 15:00:53,577 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-21 15:24:11,946 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-21 15:28:28,889 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-26 15:26:43,042 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-26 15:28:37,670 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 65, in upload_file
    return redirect(url_for('index'))
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2018-08-26 15:35:46,550 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 65, in upload_file
    return redirect(url_for('maion.index'))
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2018-08-27 17:04:52,817 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:06:02,333 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:16:48,100 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:16:57,477 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:19:17,636 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:20:45,438 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:26:26,073 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:26:31,400 ERROR: Exception on /main/index [GET] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 14, in index
    if user.is_parent_user:
AttributeError: 'list' object has no attribute 'is_parent_user'
2018-08-27 17:27:29,247 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:27:32,836 ERROR: Exception on /main/index [GET] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 13, in index
    user = load_user(id)
  File "/Users/darren/PycharmProjects/modern-money-box/app/models.py", line 39, in load_user
    return User.query.get(int(id))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'builtin_function_or_method'
2018-08-27 17:28:03,968 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
