2018-08-27 17:31:14,424 ERROR: Exception on /main/index [GET] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 32, in index
    if len(user.accounts) > 0:
TypeError: object of type 'AppenderBaseQuery' has no len()
2018-08-27 17:31:15,361 ERROR: Exception on /main/index [GET] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 32, in index
    if len(user.accounts) > 0:
TypeError: object of type 'AppenderBaseQuery' has no len()
2018-08-27 17:31:16,356 ERROR: Exception on /main/index [GET] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 32, in index
    if len(user.accounts) > 0:
TypeError: object of type 'AppenderBaseQuery' has no len()
2018-08-27 17:31:30,592 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:35:08,052 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:35:22,985 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 79, in upload_file
    for row in csv_reader:
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
2018-08-27 17:36:00,002 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:36:11,866 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 79, in upload_file
    for row in csv_reader:
_csv.Error: iterator should return strings, not int (did you open the file in text mode?)
2018-08-27 17:38:57,107 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:39:05,111 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 78, in upload_file
    text = [line.decode('utf-8') for line in file.read_lines()]
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/werkzeug/datastructures.py", line 2745, in __getattr__
    return getattr(self.stream, name)
AttributeError: 'SpooledTemporaryFile' object has no attribute 'read_lines'
2018-08-27 17:39:16,224 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
