2018-08-27 17:51:19,265 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:51:24,389 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 90, in upload_file
    print(row[1])
IndexError: list index out of range
2018-08-27 17:51:49,480 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:51:52,217 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 84, in upload_file
    content = content.encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'
2018-08-27 17:53:22,887 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:53:26,603 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 89, in upload_file
    print(row[0])
IndexError: list index out of range
2018-08-27 18:38:57,667 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 18:39:33,630 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 18:39:53,483 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 93, in upload_file
    print(row[3])
IndexError: list index out of range
2018-08-27 18:40:06,777 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 20:42:41,233 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 08:55:28,790 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 08:55:31,713 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 08:55:34,345 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 08:56:17,539 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 08:57:45,835 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 08:58:04,432 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 08:58:09,108 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 08:58:14,070 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 08:59:27,620 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 08:59:42,843 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 09:01:02,531 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 09:01:08,656 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 09:02:21,341 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-28 09:02:33,048 ERROR: Exception on /auth/login [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/PycharmProjects/modern-money-box/app/auth/routes.py", line 20, in login
    print ("is parent?:" + str(user.is_parent_user))
AttributeError: 'NoneType' object has no attribute 'is_parent_user'
2018-08-28 09:11:23,850 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
