2018-08-27 17:39:29,214 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 78, in upload_file
    text = [line.decode('utf-8') for line in file.read()]
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 78, in <listcomp>
    text = [line.decode('utf-8') for line in file.read()]
AttributeError: 'int' object has no attribute 'decode'
2018-08-27 17:42:18,705 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:42:36,315 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 84, in upload_file
    for row in csv_reader:
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 65, in utf_8_encoder
    yield line.encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'
2018-08-27 17:44:37,467 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:44:54,697 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 83, in upload_file
    csv_reader = csv.reader(file.encode('utf-8'), delimiter=',', )
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/werkzeug/datastructures.py", line 2745, in __getattr__
    return getattr(self.stream, name)
AttributeError: 'SpooledTemporaryFile' object has no attribute 'encode'
2018-08-27 17:48:37,256 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:48:49,487 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 88, in upload_file
    print(row[1])
IndexError: list index out of range
2018-08-27 17:49:24,633 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:49:34,775 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 89, in upload_file
    print(row[1])
IndexError: list index out of range
2018-08-27 17:50:02,392 INFO: Moneybox startup [in /Users/darren/PycharmProjects/modern-money-box/app/__init__.py:55]
2018-08-27 17:50:08,174 ERROR: Exception on /main/upload [POST] [in /Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/darren/anaconda3/envs/heroku-webapp/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/darren/PycharmProjects/modern-money-box/app/main/routes.py", line 89, in upload_file
    print(row[1])
IndexError: list index out of range
